# Exported from Render on 2024-07-24T12:59:29Z
services:
- type: web
  name: czar-weather-app
  runtime: static
  repo: https://github.com/chigaemez/React-weather-app
  buildCommand: yarn; yarn build
  staticPublishPath: dist
version: "1"
